---
title: "Análisis de Conjuntos Frecuentes"
author: "Michelle Audirac"
date: "primavera 2018"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, warning=FALSE, message=FALSE, echo=FALSE}
library(readr)
library(methods)
library(arules)
library(arulesViz)
library(dplyr)
library(tidyr)
library(ggplot2)
```

# Ejercicio 1

```{r}
rm(list=ls())
```

```{r}
rec <- read_csv('../../../datos/recetas/srep00196-s3.csv')
str(rec)
```

```{r}
regions <- unique(rec$region)
regions
```

```{r}
rec_tbl <- rec
rec_tbl$id <- 1:nrow(rec_tbl)
rec_tbl <- gather(rec_tbl, 'key', 'ingr', 2:33)
rec_tbl <- na.omit(rec_tbl)

rec_tbl %>% filter(id == '1')
```

```{r}
rec_tbl %<>% 
  mutate(region = as.factor(region)) %>% 
  mutate(id = as.character(id)) %>% 
  mutate(key = as.factor(key)) %>% 
  mutate(ingr = as.factor(ingr))
head(rec_tbl)
```

```{r}
ingr <- rec_tbl %>% 
  group_by(region, ingr) %>%
  summarise(n  = n()) %>%
  mutate(prop = n / nrow(rec)) %>%
  arrange(desc(n))

DT::datatable(ingr %>%
  mutate_if(is.numeric, funs(round(., 3))))
```

```{r}
rec_ls <- list()
for (r in regions) {
  rec_r <- rec[rec$region == r, -1]
  ls <- apply(rec_r, 1, function(x) as.character(x[!is.na(x)]))
  rec_ls[[r]] <- ls
}
```

```{r}
#rec_ls <- apply(rec, 1, function(x) as.character(x[!is.na(x)]))
head(rec_ls$African)
```

Ver conjuntos frecuentes por region

```{r, message = FALSE, results=FALSE}
pars <- list(supp = 0.25, target='frequent itemsets')
ap_ls <- lapply(rec_ls, apriori, parameter = pars)

#ap <- apriori(rec_ls, parameter = pars)
```

Veamos algunos conjuntos frecuentes de tamaño 1:
  
```{r, message = FALSE, collapse = TRUE}
ap_1_ls <- lapply(ap_ls, function(ap) {subset(ap, size(ap) == 1)})
lapply(ap_1_ls, length)

# ap_1 <- subset(ap, size(ap) == 1) 
# length(ap_1)
```

```{r}
lapply(ap_1_ls, function(ap_1) {inspect(sort(ap_1, by='support'))}) 

# inspect(sort(ap_1, by='support')) 
```

Algunas de tamaño 2 y 3:
  
```{r, message = FALSE, collapse = TRUE}
ap_2_ls <- lapply(ap_ls, function(ap) {subset(ap, size(ap) == 2)})
lapply(ap_2_ls, length)

# ap_2 <- subset(ap, size(ap) == 2)
# length(ap_2)
```

```{r}
ap_2_ls <- lapply(ap_2_ls, function(ap_2) {inspect(sort(ap_2, by='support'))}) 

#inspect(sort(ap_2, by='support'))
```

```{r, message = FALSE, results=FALSE}
pars <- list(supp = 0.1, confidence = 0.20, target='rules', 
             ext = TRUE, minlen = 2)

reglas_ls <- lapply(rec_ls, apriori, parameter = pars)

#reglas <- apriori(rec_ls, parameter = pars)
```

```{r}
lapply(reglas_ls, inspect)

#inspect(reglas)
```

# Ejercicio 2

```{r}
library(tidygraph)
library(ggraph)
```

```{r}
rm(list=ls())
```

```{r}
data(Groceries) # del paquete arules
class(Groceries)
lista_mb <- as(Groceries, 'list')
```

```{r}
agregar_hyperlift <- function(reglas, trans){
  quality(reglas) <- cbind(quality(reglas), 
    hyper_lift = interestMeasure(reglas, measure = "hyperLift", 
    transactions = trans))
  reglas
}
```

```{r}
pars <- list(support = 0.001,
             confidence = 0.1,
             minlen = 2,
             target='rules', ext = TRUE)
pars
```

```{r}
b_reglas <- apriori(lista_mb, parameter = pars)
b_reglas
```

```{r}
b_reglas <- agregar_hyperlift(b_reglas, lista_mb)
b_reglas
```

```{r}
b_reglas_lift <- subset(b_reglas, 
                        hyper_lift > 1.75 & confidence > 0.1)
b_reglas_lift
```

```{r}
reglas_f <- subset(b_reglas_lift, size(b_reglas_lift)==2)
reglas_f
```

```{r}
df_reglas <- reglas_f %>% DATAFRAME %>% rename(from=LHS, to=RHS) %>% as_data_frame
df_reglas$weight <- log(df_reglas$hyper_lift)
df_reglas
```

```{r}
graph_1 <- as_tbl_graph(df_reglas) %>%
  mutate(centrality = centrality_degree(mode = "all")) 
graph_1
```

```{r}
ggraph(graph_1, layout = 'fr', start.temp=100) +
  geom_edge_link(aes(alpha=lift), 
                 colour = 'red',
                 arrow = arrow(length = unit(4, 'mm'))) + 
  geom_node_point(aes(size = centrality, colour = centrality)) + 
  geom_node_text(aes(label = name), size=4,
                 colour = 'gray20', repel=TRUE) +
  theme_graph()
```
